### ISSUE TITLE
Do you need any help building/fixing something?

### ISSUE THREAD

**Issue by herou** [OffchainLabs/token-bridge-contracts#15]
Substrate/rust developer here

Contributor on different Substrate/Rust repos: https://github.com/herou
1- Converted substrate all the recipes from frame v1 o v2 : https://github.com/JoshOrndorff/recipes/pull/471 (It took me 6 months)
2- Winner of one of Web3 grants and delivered it on time: https://github.com/w3f/Grant-Milestone-Delivery/pull/599

Let me know!

**Comment by gzeoneth** [comment]
We don't have a bounty program yet but feel free to apply https://offchainlabs.com/careers/
